apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-alpine:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trashedresources-config
  namespace: system #TODO: Add dinamic namespace
data:
  namespacesToIgnore: istio-system; kube-node-lease; kube-public; kube-system
  actionsToObserve: delete; update
  kindsToObserve: Deployment; Secret; ConfigMap
  minutesToKeep: "1" #optional, default is 60. Value is in minutes. It defines how long the TrashedResource will be kept before being deleted.
  hoursToKeep: "0" #optional, default is 0. Value is in hours. It defines how long the TrashedResource will be kept before being deleted.
  daysToKeep: "0" #optional, default is 0. Value is in day (or days). It defines how long the TrashedResource will be kept before being deleted.

